import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import CustomCursor from "@/components/CustomCursor";
import Footer from "@/components/Footer";
import Home from "@/components/Pages/Home";

import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "../scss/index.scss";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <>
          <Header variant={""} />
          <Home />
          {children}
          <CustomCursor />
          <Footer />
        </>
      </body>
    </html>
  );
}
